# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84d8368302c5037bec26780c938b67c368fdead1c9da358d25520a0ad22a003df24efa1682db80dd1eeee20220747a1b211bde3a2824b4c5741b8ed3d1536fe1

test:
  secret_key_base: 6f120878c71f42dc05461edffb39808c80c330786b1800716a111c89dff983e4e19becb73cabc72e7d3a3f51f876b6b2014f1c16b1afa4cfa47f68ea689fca24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
